# Generated by Django 2.2.28 on 2026-03-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_cleanup_duplicate_registration_profiles'),
        ('program', '0031_add_link_title_to_programmoduleobj'),
    ]

    operations = [
    ]
