# Generated by Django 2.2.28 on 2026-03-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_merge_20260315_0546'),
        ('program', '0034_auto_20260317_2119'),
    ]

    operations = [
    ]
